spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapper/*.xml
user:
  address:
    max-count: 20
